package com.mycompany.sumarnum;
import java.util.HashMap;
import java.util.Scanner;
public class Sumarnum {
    public static HashMap<Integer, String> numerosEnEspanol() {
        HashMap<Integer, String> numerosMap = new HashMap<>();
        numerosMap.put(1, "uno");
        numerosMap.put(2, "dos");
        numerosMap.put(3, "tres");
        numerosMap.put(4, "cuatro");
        numerosMap.put(5, "cinco");
        numerosMap.put(6, "seis");
        numerosMap.put(7, "siete");
        numerosMap.put(8, "ocho");
        numerosMap.put(9, "nueve");
        numerosMap.put(10, "diez");
        numerosMap.put(11, "once");
        numerosMap.put(12, "doce");
        numerosMap.put(13, "trece");
        numerosMap.put(14, "catorce");
        numerosMap.put(15, "quince");
        numerosMap.put(16, "dieciséis");
        numerosMap.put(17, "diecisiete");
        numerosMap.put(18, "dieciocho");
        numerosMap.put(19, "diecinueve");
        numerosMap.put(20, "veinte");
        numerosMap.put(21, "veintiuno");
        numerosMap.put(22, "veintidós");
        numerosMap.put(23, "veintitrés");
        numerosMap.put(24, "veinticuatro");
        numerosMap.put(25, "veinticinco");
        numerosMap.put(26, "veintiséis");
        numerosMap.put(27, "veintisiete");
        numerosMap.put(28, "veintiocho");
        numerosMap.put(29, "veintinueve");
        numerosMap.put(30, "treinta");
        numerosMap.put(31, "treinta y uno");
        numerosMap.put(32, "treinta y dos");
        numerosMap.put(33, "treinta y tres");
        numerosMap.put(34, "treinta y cuatro");
        numerosMap.put(35, "treinta y cinco");
        numerosMap.put(36, "treinta y seis");
        numerosMap.put(37, "treinta y siete");
        numerosMap.put(38, "treinta y ocho");
        numerosMap.put(39, "treinta y nueve");
        numerosMap.put(40, "cuarenta");
        numerosMap.put(41, "cuarenta y uno");
        numerosMap.put(42, "cuarenta y dos");
        numerosMap.put(43, "cuarenta y tres");
        numerosMap.put(44, "cuarenta y cuatro");
        numerosMap.put(45, "cuarenta y cinco");
        numerosMap.put(46, "cuarenta y seis");
        numerosMap.put(47, "cuarenta y siete");
        numerosMap.put(48, "cuarenta y ocho");
        numerosMap.put(49, "cuarenta y nueve");
        numerosMap.put(50, "cincuenta");
        numerosMap.put(51, "cincuenta y uno");
        numerosMap.put(52, "cincuenta y dos");
        numerosMap.put(53, "cincuenta y tres");
        numerosMap.put(54, "cincuenta y cuatro");
        numerosMap.put(55, "cincuenta y cinco");
        numerosMap.put(56, "cincuenta y seis");
        numerosMap.put(57, "cincuenta y siete");
        numerosMap.put(58, "cincuenta y ocho");
        numerosMap.put(59, "cincuenta y nueve");
        numerosMap.put(60, "sesenta");
        numerosMap.put(61, "sesenta y uno");
        numerosMap.put(62, "sesenta y dos");
        numerosMap.put(63, "sesenta y tres");
        numerosMap.put(64, "sesenta y cuatro");
        numerosMap.put(65, "sesenta y cinco");
        numerosMap.put(66, "sesenta y seis");
        numerosMap.put(67, "sesenta y siete");
        numerosMap.put(68, "sesenta y ocho");
        numerosMap.put(69, "sesenta y nueve");
        numerosMap.put(70, "setenta");
        numerosMap.put(71, "setenta y uno");
        numerosMap.put(72, "setenta y dos");
        numerosMap.put(73, "setenta y tres");
        numerosMap.put(74, "setenta y cuatro");
        numerosMap.put(75, "setenta y cinco");
        numerosMap.put(76, "setenta y seis");
        numerosMap.put(77, "setenta y siete");
        numerosMap.put(78, "setenta y ocho");
        numerosMap.put(79, "setenta y nueve");
        numerosMap.put(80, "ochenta");
        numerosMap.put(81, "ochenta y uno");
        numerosMap.put(82, "ochenta y dos");
        numerosMap.put(83, "ochenta y tres");
        numerosMap.put(84, "ochenta y cuatro");
        numerosMap.put(85, "ochenta y cinco");
        numerosMap.put(86, "ochenta y seis");
        numerosMap.put(87, "ochenta y siete");
        numerosMap.put(88, "ochenta y ocho");
        numerosMap.put(89, "ochenta y nueve");
        numerosMap.put(90, "noventa");
        numerosMap.put(91, "noventa y uno");
        numerosMap.put(92, "noventa y dos");
        numerosMap.put(93, "noventa y tres");
        numerosMap.put(94, "noventa y cuatro");
        numerosMap.put(95, "noventa y cinco");
        numerosMap.put(96, "noventa y seis");
        numerosMap.put(97, "noventa y siete");
        numerosMap.put(98, "noventa y ocho");
        numerosMap.put(99, "noventa y nueve");
        numerosMap.put(100, "cien");
        return numerosMap;
    }
    public static HashMap<Integer, String> numerosEnIngles() {
        HashMap<Integer, String> numerosMap = new HashMap<>();
        numerosMap.put(1, "one");
        numerosMap.put(2, "two");
        numerosMap.put(3, "three");
        numerosMap.put(4, "four");
        numerosMap.put(5, "five");
        numerosMap.put(6, "six");
        numerosMap.put(7, "seven");
        numerosMap.put(8, "eight");
        numerosMap.put(9, "nine");
        numerosMap.put(10, "ten");
        numerosMap.put(11, "eleven");
        numerosMap.put(12, "twelve");
        numerosMap.put(13, "thirteen");
        numerosMap.put(14, "fourteen");
        numerosMap.put(15, "fifteen");
        numerosMap.put(16, "sixteen");
        numerosMap.put(17, "seventeen");
        numerosMap.put(18, "eighteen");
        numerosMap.put(19, "nineteen");
        numerosMap.put(20, "twenty");
        numerosMap.put(21, "twenty-one");
        numerosMap.put(22, "twenty-two");
        numerosMap.put(23, "twenty-three");
        numerosMap.put(24, "twenty-four");
        numerosMap.put(25, "twenty-five");
        numerosMap.put(26, "twenty-six");
        numerosMap.put(27, "twenty-seven");
        numerosMap.put(28, "twenty-eight");
        numerosMap.put(29, "twenty-nine");
        numerosMap.put(30, "thirty");
        numerosMap.put(31, "thirty-one");
        numerosMap.put(32, "thirty-two");
        numerosMap.put(33, "thirty-three");
        numerosMap.put(34, "thirty-four");
        numerosMap.put(35, "thirty-five");
        numerosMap.put(36, "thirty-six");
        numerosMap.put(37, "thirty-seven");
        numerosMap.put(38, "thirty-eight");
        numerosMap.put(39, "thirty-nine");
        numerosMap.put(40, "forty");
        numerosMap.put(41, "forty-one");
        numerosMap.put(42, "forty-two");
        numerosMap.put(43, "forty-three");
        numerosMap.put(44, "forty-four");
        numerosMap.put(45, "forty-five");
        numerosMap.put(46, "forty-six");
        numerosMap.put(47, "forty-seven");
        numerosMap.put(48, "forty-eight");
        numerosMap.put(49, "forty-nine");
        numerosMap.put(50, "fifty");
        numerosMap.put(51, "fifty-one");
        numerosMap.put(52, "fifty-two");
        numerosMap.put(53, "fifty-three");
        numerosMap.put(54, "fifty-four");
        numerosMap.put(55, "fifty-five");
        numerosMap.put(56, "fifty-six");
        numerosMap.put(57, "fifty-seven");
        numerosMap.put(58, "fifty-eight");
        numerosMap.put(59, "fifty-nine");
        numerosMap.put(60, "sixty");
        numerosMap.put(61, "sixty-one");
        numerosMap.put(62, "sixty-two");
        numerosMap.put(63, "sixty-three");
        numerosMap.put(64, "sixty-four");
        numerosMap.put(65, "sixty-five");
        numerosMap.put(66, "sixty-six");
        numerosMap.put(67, "sixty-seven");
        numerosMap.put(68, "sixty-eight");
        numerosMap.put(69, "sixty-nine");
        numerosMap.put(70, "seventy");
        numerosMap.put(71, "seventy-one");
        numerosMap.put(72, "seventy-two");
        numerosMap.put(73, "seventy-three");
        numerosMap.put(74, "seventy-four");
        numerosMap.put(75, "seventy-five");
        numerosMap.put(76, "seventy-six");
        numerosMap.put(77, "seventy-seven");
        numerosMap.put(78, "seventy-eight");
        numerosMap.put(79, "seventy-nine");
        numerosMap.put(80, "eighty");
        numerosMap.put(81, "eighty-one");
        numerosMap.put(82, "eighty-two");
        numerosMap.put(83, "eighty-three");
        numerosMap.put(84, "eighty-four");
        numerosMap.put(85, "eighty-five");
        numerosMap.put(86, "eighty-six");
        numerosMap.put(87, "eighty-seven");
        numerosMap.put(88, "eighty-eight");
        numerosMap.put(89, "eighty-nine");
        numerosMap.put(90, "ninety");
        numerosMap.put(91, "ninety-one");
        numerosMap.put(92, "ninety-two");
        numerosMap.put(93, "ninety-three");
        numerosMap.put(94, "ninety-four");
        numerosMap.put(95, "ninety-five");
        numerosMap.put(96, "ninety-six");
        numerosMap.put(97, "ninety-seven");
        numerosMap.put(98, "ninety-eight");
        numerosMap.put(99, "ninety-nine");
        numerosMap.put(100, "one hundred");
        return numerosMap;
    }
    public static HashMap<Integer, String>textos(String idioma){
    switch(idioma){
        case "Espanol":
            return numerosEnEspanol();
        case "English":
            return numerosEnIngles();
    }
    return null;
    }
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Espanol o English");
        String idioma = sc.next();
        HashMap<Integer, String> letras = textos(idioma);
        System.out.println("Ingresa un numero del 1 al 100:");
        int a = sc.nextInt();
        System.out.println("Ingresa un segundo numero del 1 al 100:");
        int b = sc.nextInt();
        int c = a+b;
        String numA = letras.get(a);
        String numB = letras.get(b);
        String SUM = letras.get(c);
        if ("Espanol".equalsIgnoreCase(idioma)){
        System.out.println("La suma de " + numA + " y " + numB + " es " + SUM);
        }else if ("English".equalsIgnoreCase(idioma)){
        System.out.println("The sum of " + numA + " and " + numB + " is " + SUM);
        }
    }
}
